"""All paper figures generated here - one function per figure."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

FIG_DIR = Path("results/figures")
FIG_DIR.mkdir(parents=True, exist_ok=True)

sns.set_theme(style="whitegrid", palette="muted")


def _seed_noise_std(baseline: str = "lagged") -> float | None:
    """Estimate the cross-year mean of the per-year std of aware-vs-<baseline>%.

    Tries sources in order:
    1. data/processed/seed_sensitivity_seed*.parquet — per-seed Phase-1
       dispatch caches. Preferred because they're regenerated by every fresh
       06 run; v1.3 PINN-predicted costs match CoolProp truth to ~1e-7
       relative error so the noise band computed from PINN costs is
       interchangeable with the post-Phase-2 truth-based one.
    2. results/tables/seed_sensitivity_summary.csv — the published summary
       written by scripts/06_seed_sensitivity.py at the very end of Phase 2.
       Used only when no Phase-1 caches are on disk (e.g. after a clean
       checkout from git).

    Returns None if neither source is usable.
    """
    seed_files = sorted(Path("data/processed").glob("seed_sensitivity_seed*.parquet"))
    seed_files = [p for p in seed_files if "partial" not in p.name]
    if seed_files:
        try:
            rows = []
            for path in seed_files:
                try:
                    seed_id = int(path.stem.replace("seed_sensitivity_seed", ""))
                except ValueError:
                    continue
                df = pd.read_parquet(path)
                if "_strategy" not in df.columns or "time" not in df.columns:
                    continue
                df["time"] = pd.to_datetime(df["time"], utc=True)
                df["year"] = df["time"].dt.year
                pivot = df.groupby(["year", "_strategy"])["cost_eur"].sum().unstack()
                if not ({"aware", baseline} <= set(pivot.columns)):
                    continue
                for year, row in pivot.iterrows():
                    rows.append({
                        "seed": seed_id,
                        "year": int(year),
                        "saving_pct": (row[baseline] - row["aware"]) / row[baseline] * 100.0,
                    })
            if rows:
                per_year_std = pd.DataFrame(rows).groupby("year")["saving_pct"].std()
                return float(per_year_std.mean())
        except Exception:
            pass

    summary_path = Path("results/tables/seed_sensitivity_summary.csv")
    if summary_path.exists():
        try:
            df = pd.read_csv(summary_path)
            rows = df[df["baseline"] == baseline]
            if not rows.empty and "std" in rows.columns:
                return float(rows["std"].mean())
        except Exception:
            pass

    return None


def fig_carbon_sweep(sweep_df: pd.DataFrame) -> None:
    """v1.3 headline figure: aware-vs-lagged saving + temporal-arbitrage collapse.

    Two panels share an x-axis (carbon price):

    Panel A — composition-awareness value: aware vs lagged-blind baseline.
              The lagged baseline is the realistic operator assumption ("I know
              last cargo's composition but not today's blend"). Per-year lines
              are drawn faintly; the cross-year mean is bold. If a fresh
              ``seed_sensitivity_summary.csv`` exists in results/tables/, a
              ±2σ seed-noise band is overlaid as a horizontal shaded region,
              giving the reader the threshold above which the saving is
              statistically meaningful.

    Panel B — temporal-arbitrage value: aware vs constant-flow baseline. This
              collapses from ~16% at zero carbon to <1% at any positive
              carbon price, because emissions are pinned by the demand
              constraint and dominate the cost — the surprising finding that
              motivates the composition story.

    ``sweep_df`` must have columns: price_co2_eur_per_t, year,
    aware, horizon, lagged, annual, constant, saving_vs_lagged_pct.
    """
    sweep = sweep_df.copy()
    sweep["saving_vs_constant_pct"] = (
        (sweep["constant"] - sweep["aware"]) / sweep["constant"] * 100
    )

    years = sorted(sweep["year"].unique())
    palette = sns.color_palette("muted", n_colors=len(years))

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.5, 4.6), sharex=True)

    # ---- Panel A: aware vs lagged ------------------------------------------
    for year, color in zip(years, palette):
        sub = sweep[sweep["year"] == year].sort_values("price_co2_eur_per_t")
        ax1.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_lagged_pct"],
            marker="o", linewidth=1.0, alpha=0.45, color=color, label=str(year),
        )
    mean_lagged = sweep.groupby("price_co2_eur_per_t")["saving_vs_lagged_pct"].mean()
    ax1.plot(
        mean_lagged.index, mean_lagged.values,
        color="black", linewidth=2.4, marker="s", label="3-yr mean", zorder=10,
    )

    # ±2σ seed-noise band — drawn if we can compute a cross-year mean std
    # from either the published summary CSV or the Phase-1 seed parquets.
    # The carbon-sweep is at one composition seed, so the band is the implicit
    # uncertainty around every blue/orange/green dot in the figure.
    typical_std = _seed_noise_std("lagged")
    if typical_std is not None and typical_std > 0:
        ax1.axhspan(
            -2 * typical_std, 2 * typical_std,
            color="grey", alpha=0.12, zorder=0,
            label=f"±2σ seed noise (~±{2*typical_std:.1f}%)",
        )

    if 80.0 in mean_lagged.index:
        ax1.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
    ax1.axhline(0.0, color="grey", linewidth=0.8)
    ax1.set_xlabel("Carbon price (EUR / tCO$_2$)")
    ax1.set_ylabel("Saving vs lagged-composition baseline (%)")
    ax1.set_title("A. Composition-awareness value\n(aware vs lagged-blind)")
    ax1.legend(loc="best", fontsize=8, ncol=2)

    # ---- Panel B: aware vs constant (the surprising collapse) --------------
    for year, color in zip(years, palette):
        sub = sweep[sweep["year"] == year].sort_values("price_co2_eur_per_t")
        ax2.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_constant_pct"],
            marker="o", linewidth=1.0, alpha=0.45, color=color, label=str(year),
        )
    mean_const = sweep.groupby("price_co2_eur_per_t")["saving_vs_constant_pct"].mean()
    ax2.plot(
        mean_const.index, mean_const.values,
        color="black", linewidth=2.4, marker="s", label="3-yr mean", zorder=10,
    )
    if 80.0 in mean_const.index:
        ax2.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
    ax2.axhline(0.0, color="grey", linewidth=0.8)
    ax2.set_xlabel("Carbon price (EUR / tCO$_2$)")
    ax2.set_ylabel("Saving vs constant-flow baseline (%)")
    ax2.set_title("B. Temporal-arbitrage value\n(aware vs constant-flow)")
    ax2.legend(loc="best", fontsize=8, ncol=2)

    # Shared EU-ETS annotation in figure coordinates so both panels reference
    # the same x position without overlapping panel content.
    fig.text(
        0.5, 0.965, r"Vertical dashed line: current EU ETS (~€80/tCO$_2$)",
        ha="center", va="top", fontsize=9, color="firebrick",
    )

    fig.tight_layout(rect=(0, 0, 1, 0.94))
    fig.savefig(FIG_DIR / "fig6_carbon_sweep.pdf")
    plt.close(fig)


def fig_cost_delta(
    aware_df: pd.DataFrame,
    blind_df: pd.DataFrame,
) -> None:
    """Bar chart of cost savings (aware vs blind) by month."""
    delta = blind_df["cost_eur"] - aware_df["cost_eur"]
    monthly = delta.resample("ME").sum()
    fig, ax = plt.subplots(figsize=(10, 4))
    monthly.plot(kind="bar", ax=ax, color="steelblue")
    ax.set_xlabel("Month")
    ax.set_ylabel("Cost saving (EUR)")
    ax.set_title("Composition-aware vs composition-blind dispatch cost saving")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig1_cost_delta.pdf")
    plt.close(fig)


def fig_sensitivity(sensitivity_df: pd.DataFrame) -> None:
    """Cost savings vs composition and price-regime metrics."""
    panels = [
        ("variability", "std(CH4 mole fraction)"),
        ("price_volatility", "price volatility (EUR/MWh)"),
        ("price_ch4_corr", "corr(price, CH4)"),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(13, 4), sharey=True)
    for ax, (col, label) in zip(axes, panels, strict=True):
        ax.scatter(sensitivity_df[col], sensitivity_df["saving_eur"], alpha=0.65)
        corr = sensitivity_df[[col, "saving_eur"]].corr().iloc[0, 1]
        ax.set_xlabel(label)
        ax.set_title(f"r = {corr:.2f}")
    axes[0].set_ylabel("Total cost saving (EUR)")
    fig.suptitle("Dispatch saving drivers by rolling window", y=1.02)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig2_sensitivity.pdf")
    plt.close(fig)


def fig_load_shift_heatmap(
    aware_df: pd.DataFrame,
    blind_df: pd.DataFrame,
    timeseries_df: pd.DataFrame,
) -> None:
    """Heatmap: (price quantile, methane number) -> load shift."""
    price_q = pd.qcut(timeseries_df["price_eur_mwh"], q=5, labels=False)
    ch4 = timeseries_df["CH4"]
    ch4_q = pd.qcut(ch4, q=5, labels=False)
    shift = aware_df["m_dot"] - blind_df["m_dot"]
    pivot = pd.DataFrame({"price_q": price_q, "ch4_q": ch4_q, "shift": shift})
    table = pivot.groupby(["price_q", "ch4_q"])["shift"].mean().unstack()
    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(table, annot=True, fmt=".1f", ax=ax, cmap="RdBu_r", center=0)
    ax.set_xlabel("CH4 quantile (proxy for methane number)")
    ax.set_ylabel("Price quantile")
    ax.set_title("Load shift: aware - blind (kg/s)")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig3_load_shift.pdf")
    plt.close(fig)


def fig_surrogate_eval(eval_df: pd.DataFrame) -> None:
    """Bar chart of per-channel MAE, RMSE, R² from the held-out test split."""
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    for ax, metric in zip(axes, ["MAE", "RMSE", "R2"]):
        ax.bar(eval_df["channel"], eval_df[metric], color="steelblue")
        ax.set_title(metric)
        ax.set_xlabel("Output channel")
        ax.tick_params(axis="x", rotation=30)
    axes[0].set_ylabel("Error (physical units)")
    axes[2].set_ylabel("R²")
    fig.suptitle("PINN surrogate — held-out test set (10%)")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig5_surrogate_eval.pdf")
    plt.close(fig)


def fig_surrogate_fidelity(fidelity_df: pd.DataFrame) -> None:
    """PINN-predicted cost error vs CoolProp ground truth."""
    err_pct = fidelity_df["pinn_cost_eur"] / fidelity_df["true_cost_eur"] - 1.0
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(err_pct * 100, bins=40, color="steelblue", edgecolor="white")
    ax.axvline(1.0, color="red", linestyle="--", label="1% threshold")
    ax.axvline(-1.0, color="red", linestyle="--")
    ax.set_xlabel("Cost prediction error (%)")
    ax.set_ylabel("Count")
    ax.set_title("PINN surrogate fidelity vs CoolProp ground truth")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig4_fidelity.pdf")
    plt.close(fig)
