"""All paper figures generated here - one function per figure."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

FIG_DIR = Path("results/figures")
FIG_DIR.mkdir(parents=True, exist_ok=True)

sns.set_theme(style="whitegrid", palette="muted")


def _seed_stats_per_year(
    baseline: str = "lagged",
) -> tuple[dict[int, float], dict[int, float]] | None:
    """Return ({year: mean}, {year: std}) of aware-vs-<baseline>% across seeds.

    The mean is the seed-mean point estimate (the value to trust as the
    best estimator of "what saving this year would produce on average across
    cargo schedules"). The single-seed carbon sweep is one draw from this
    distribution and may sit anywhere within the std band.
    """
    seed_files = sorted(Path("data/processed").glob("seed_sensitivity_seed*.parquet"))
    seed_files = [p for p in seed_files if "partial" not in p.name]
    if not seed_files:
        return None
    try:
        rows = []
        for path in seed_files:
            try:
                seed_id = int(path.stem.replace("seed_sensitivity_seed", ""))
            except ValueError:
                continue
            df = pd.read_parquet(path)
            if "_strategy" not in df.columns or "time" not in df.columns:
                continue
            df["time"] = pd.to_datetime(df["time"], utc=True)
            df["year"] = df["time"].dt.year
            pivot = df.groupby(["year", "_strategy"])["cost_eur"].sum().unstack()
            if not ({"aware", baseline} <= set(pivot.columns)):
                continue
            for year, row in pivot.iterrows():
                rows.append({
                    "seed": seed_id,
                    "year": int(year),
                    "saving_pct": (row[baseline] - row["aware"]) / row[baseline] * 100.0,
                })
        if rows:
            g = pd.DataFrame(rows).groupby("year")["saving_pct"]
            means = {int(y): float(v) for y, v in g.mean().items()}
            stds = {int(y): float(v) for y, v in g.std().items()}
            return means, stds
    except Exception:
        pass
    return None


def _seed_noise_per_year(baseline: str = "lagged") -> dict[int, float] | None:
    """Return {year: std of aware-vs-<baseline>% across seeds} for the year-by-year
    error bars in fig6 Panel A.

    Preserves the per-year noise structure rather than collapsing to a single
    scalar — 2022 (energy crisis) has materially higher cross-seed variance
    than 2021/2023, and the figure should show that honestly.
    """
    seed_files = sorted(Path("data/processed").glob("seed_sensitivity_seed*.parquet"))
    seed_files = [p for p in seed_files if "partial" not in p.name]
    if not seed_files:
        return None
    try:
        rows = []
        for path in seed_files:
            try:
                seed_id = int(path.stem.replace("seed_sensitivity_seed", ""))
            except ValueError:
                continue
            df = pd.read_parquet(path)
            if "_strategy" not in df.columns or "time" not in df.columns:
                continue
            df["time"] = pd.to_datetime(df["time"], utc=True)
            df["year"] = df["time"].dt.year
            pivot = df.groupby(["year", "_strategy"])["cost_eur"].sum().unstack()
            if not ({"aware", baseline} <= set(pivot.columns)):
                continue
            for year, row in pivot.iterrows():
                rows.append({
                    "seed": seed_id,
                    "year": int(year),
                    "saving_pct": (row[baseline] - row["aware"]) / row[baseline] * 100.0,
                })
        if rows:
            per_year = pd.DataFrame(rows).groupby("year")["saving_pct"].std()
            return {int(y): float(s) for y, s in per_year.items()}
    except Exception:
        pass
    return None


def _seed_noise_std(baseline: str = "lagged") -> float | None:
    """Estimate the cross-year mean of the per-year std of aware-vs-<baseline>%.

    Tries sources in order:
    1. data/processed/seed_sensitivity_seed*.parquet — per-seed Phase-1
       dispatch caches. Preferred because they're regenerated by every fresh
       06 run; v1.3 PINN-predicted costs match CoolProp truth to ~1e-7
       relative error so the noise band computed from PINN costs is
       interchangeable with the post-Phase-2 truth-based one.
    2. results/tables/seed_sensitivity_summary.csv — the published summary
       written by scripts/06_seed_sensitivity.py at the very end of Phase 2.
       Used only when no Phase-1 caches are on disk (e.g. after a clean
       checkout from git).

    Returns None if neither source is usable.
    """
    seed_files = sorted(Path("data/processed").glob("seed_sensitivity_seed*.parquet"))
    seed_files = [p for p in seed_files if "partial" not in p.name]
    if seed_files:
        try:
            rows = []
            for path in seed_files:
                try:
                    seed_id = int(path.stem.replace("seed_sensitivity_seed", ""))
                except ValueError:
                    continue
                df = pd.read_parquet(path)
                if "_strategy" not in df.columns or "time" not in df.columns:
                    continue
                df["time"] = pd.to_datetime(df["time"], utc=True)
                df["year"] = df["time"].dt.year
                pivot = df.groupby(["year", "_strategy"])["cost_eur"].sum().unstack()
                if not ({"aware", baseline} <= set(pivot.columns)):
                    continue
                for year, row in pivot.iterrows():
                    rows.append({
                        "seed": seed_id,
                        "year": int(year),
                        "saving_pct": (row[baseline] - row["aware"]) / row[baseline] * 100.0,
                    })
            if rows:
                per_year_std = pd.DataFrame(rows).groupby("year")["saving_pct"].std()
                return float(per_year_std.mean())
        except Exception:
            pass

    summary_path = Path("results/tables/seed_sensitivity_summary.csv")
    if summary_path.exists():
        try:
            df = pd.read_csv(summary_path)
            rows = df[df["baseline"] == baseline]
            if not rows.empty and "std" in rows.columns:
                return float(rows["std"].mean())
        except Exception:
            pass

    return None


def fig_carbon_sweep(sweep_df: pd.DataFrame) -> None:
    """v1.3 headline figure: aware-vs-lagged saving + temporal-arbitrage collapse.

    Two panels share an x-axis (carbon price):

    Panel A — composition-awareness value: aware vs lagged-blind baseline.
              The lagged baseline is the realistic operator assumption ("I know
              last cargo's composition but not today's blend"). Per-year lines
              are drawn faintly; the cross-year mean is bold. If a fresh
              ``seed_sensitivity_summary.csv`` exists in results/tables/, a
              ±2σ seed-noise band is overlaid as a horizontal shaded region,
              giving the reader the threshold above which the saving is
              statistically meaningful.

    Panel B — temporal-arbitrage value: aware vs constant-flow baseline. This
              collapses from ~16% at zero carbon to <1% at any positive
              carbon price, because emissions are pinned by the demand
              constraint and dominate the cost — the surprising finding that
              motivates the composition story.

    ``sweep_df`` must have columns: price_co2_eur_per_t, year,
    aware, horizon, lagged, annual, constant, saving_vs_lagged_pct.
    """
    sweep = sweep_df.copy()
    sweep["saving_vs_constant_pct"] = (
        (sweep["constant"] - sweep["aware"]) / sweep["constant"] * 100
    )

    years = sorted(sweep["year"].unique())
    palette = sns.color_palette("muted", n_colors=len(years))

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.5, 4.6), sharex=True)

    # ---- Panel A: aware vs lagged ------------------------------------------
    # Each year as its own line; at €80 we overlay a star marker showing the
    # 10-seed mean (the actual best estimate for that year), with a vertical
    # ±2σ error bar around it. The carbon-sweep dot at €80 is one draw from
    # this seed distribution and may sit anywhere within the band.
    seed_stats = _seed_stats_per_year("lagged")
    per_year_mean: dict[int, float] = seed_stats[0] if seed_stats else {}
    per_year_std: dict[int, float] = seed_stats[1] if seed_stats else {}
    for year, color in zip(years, palette):
        sub = sweep[sweep["year"] == year].sort_values("price_co2_eur_per_t")
        ax1.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_lagged_pct"],
            marker="o", linewidth=1.0, alpha=0.55, color=color, label=str(year),
        )
        if year in per_year_std:
            ax1.errorbar(
                80.0, per_year_mean[year], yerr=2 * per_year_std[year],
                fmt="*", color=color, markersize=12, markeredgecolor="black",
                markeredgewidth=0.8, ecolor=color, elinewidth=1.6,
                capsize=4, capthick=1.6, alpha=0.95, zorder=9,
            )

    mean_lagged = sweep.groupby("price_co2_eur_per_t")["saving_vs_lagged_pct"].mean()
    ax1.plot(
        mean_lagged.index, mean_lagged.values,
        color="black", linewidth=2.4, marker="s", label="3-yr mean", zorder=10,
    )

    if 80.0 in mean_lagged.index:
        ax1.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
    ax1.axhline(0.0, color="grey", linewidth=0.8)
    ax1.set_xlabel("Carbon price (EUR / tCO$_2$)")
    ax1.set_ylabel("Saving vs lagged-composition baseline (%)")
    ax1.set_title("A. Composition-awareness value\n(aware vs lagged-blind)")
    if per_year_std:
        # Proxy artist to explain the ★ marker convention in the legend.
        ax1.plot(
            [], [], marker="*", markersize=10, markeredgecolor="black",
            markeredgewidth=0.8, color="grey", linestyle="none",
            label=r"10-seed mean ± 2σ at €80",
        )
    ax1.legend(loc="best", fontsize=8, ncol=2)

    # ---- Panel B: aware vs constant (the surprising collapse) --------------
    for year, color in zip(years, palette):
        sub = sweep[sweep["year"] == year].sort_values("price_co2_eur_per_t")
        ax2.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_constant_pct"],
            marker="o", linewidth=1.0, alpha=0.45, color=color, label=str(year),
        )
    mean_const = sweep.groupby("price_co2_eur_per_t")["saving_vs_constant_pct"].mean()
    ax2.plot(
        mean_const.index, mean_const.values,
        color="black", linewidth=2.4, marker="s", label="3-yr mean", zorder=10,
    )
    if 80.0 in mean_const.index:
        ax2.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
    ax2.axhline(0.0, color="grey", linewidth=0.8)
    ax2.set_xlabel("Carbon price (EUR / tCO$_2$)")
    ax2.set_ylabel("Saving vs constant-flow baseline (%)")
    ax2.set_title("B. Temporal-arbitrage value\n(aware vs constant-flow)")
    ax2.legend(loc="best", fontsize=8, ncol=2)

    # Shared EU-ETS annotation in figure coordinates so both panels reference
    # the same x position without overlapping panel content.
    fig.text(
        0.5, 0.965, r"Vertical dashed line: current EU ETS (~€80/tCO$_2$)",
        ha="center", va="top", fontsize=9, color="firebrick",
    )

    fig.tight_layout(rect=(0, 0, 1, 0.94))
    fig.savefig(FIG_DIR / "fig6_carbon_sweep.pdf")
    plt.close(fig)


def fig_carbon_sweep_per_year(sweep_df: pd.DataFrame) -> list[Path]:
    """Per-year companion figures to fig6 — one PDF per year.

    Each figure has the same two-panel layout as fig6 but shows only one
    year's data, the ★ 10-seed mean ± 2σ marker at €80, and no 3-year mean
    line. Useful for the paper's per-year discussion sections where the
    reader needs to focus on a single year without the others overlapping.

    Saves results/figures/fig6_carbon_sweep_<year>.pdf for each year in
    ``sweep_df``. Returns the list of paths written.
    """
    sweep = sweep_df.copy()
    if "saving_vs_constant_pct" not in sweep.columns:
        sweep["saving_vs_constant_pct"] = (
            (sweep["constant"] - sweep["aware"]) / sweep["constant"] * 100
        )

    seed_stats = _seed_stats_per_year("lagged")
    per_year_mean = seed_stats[0] if seed_stats else {}
    per_year_std = seed_stats[1] if seed_stats else {}

    years = sorted(sweep["year"].unique())
    palette = sns.color_palette("muted", n_colors=len(years))
    color_for = dict(zip(years, palette))

    written: list[Path] = []
    for year in years:
        color = color_for[year]
        sub = sweep[sweep["year"] == year].sort_values("price_co2_eur_per_t")
        if sub.empty:
            continue

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10.5, 4.2), sharex=True)

        # Panel A — aware vs lagged
        ax1.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_lagged_pct"],
            marker="o", linewidth=1.6, color=color, label=f"{year} (single seed)",
        )
        if year in per_year_std:
            ax1.errorbar(
                80.0, per_year_mean[year], yerr=2 * per_year_std[year],
                fmt="*", color=color, markersize=14, markeredgecolor="black",
                markeredgewidth=0.8, ecolor=color, elinewidth=1.8,
                capsize=5, capthick=1.8, alpha=0.95, zorder=9,
                label=(
                    f"10-seed mean = {per_year_mean[year]:+.2f}% "
                    f"±2σ = {2*per_year_std[year]:.2f}%"
                ),
            )
        if 80.0 in sub["price_co2_eur_per_t"].values:
            ax1.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
        ax1.axhline(0.0, color="grey", linewidth=0.8)
        ax1.set_xlabel("Carbon price (EUR / tCO$_2$)")
        ax1.set_ylabel("Saving vs lagged-composition baseline (%)")
        ax1.set_title(f"{year} — A. Composition-awareness value")
        ax1.legend(loc="best", fontsize=8)

        # Panel B — aware vs constant-flow
        ax2.plot(
            sub["price_co2_eur_per_t"], sub["saving_vs_constant_pct"],
            marker="o", linewidth=1.6, color=color, label=str(year),
        )
        if 80.0 in sub["price_co2_eur_per_t"].values:
            ax2.axvline(80.0, color="firebrick", linestyle="--", alpha=0.6, linewidth=1.0)
        ax2.axhline(0.0, color="grey", linewidth=0.8)
        ax2.set_xlabel("Carbon price (EUR / tCO$_2$)")
        ax2.set_ylabel("Saving vs constant-flow baseline (%)")
        ax2.set_title(f"{year} — B. Temporal-arbitrage value")
        ax2.legend(loc="best", fontsize=8)

        fig.text(
            0.5, 0.96, r"Vertical dashed line: current EU ETS (~€80/tCO$_2$)",
            ha="center", va="top", fontsize=9, color="firebrick",
        )
        fig.tight_layout(rect=(0, 0, 1, 0.93))
        out_path = FIG_DIR / f"fig6_carbon_sweep_{year}.pdf"
        fig.savefig(out_path)
        plt.close(fig)
        written.append(out_path)

    return written


def fig_cost_delta(
    aware_df: pd.DataFrame,
    blind_df: pd.DataFrame,
) -> None:
    """Bar chart of cost savings (aware vs blind) by month."""
    delta = blind_df["cost_eur"] - aware_df["cost_eur"]
    monthly = delta.resample("ME").sum()
    fig, ax = plt.subplots(figsize=(10, 4))
    monthly.plot(kind="bar", ax=ax, color="steelblue")
    ax.set_xlabel("Month")
    ax.set_ylabel("Cost saving (EUR)")
    ax.set_title("Composition-aware vs composition-blind dispatch cost saving")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig1_cost_delta.pdf")
    plt.close(fig)


def fig_sensitivity(sensitivity_df: pd.DataFrame) -> None:
    """Cost savings vs composition and price-regime metrics."""
    panels = [
        ("variability", "std(CH4 mole fraction)"),
        ("price_volatility", "price volatility (EUR/MWh)"),
        ("price_ch4_corr", "corr(price, CH4)"),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(13, 4), sharey=True)
    for ax, (col, label) in zip(axes, panels, strict=True):
        ax.scatter(sensitivity_df[col], sensitivity_df["saving_eur"], alpha=0.65)
        corr = sensitivity_df[[col, "saving_eur"]].corr().iloc[0, 1]
        ax.set_xlabel(label)
        ax.set_title(f"r = {corr:.2f}")
    axes[0].set_ylabel("Total cost saving (EUR)")
    fig.suptitle("Dispatch saving drivers by rolling window", y=1.02)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig2_sensitivity.pdf")
    plt.close(fig)


def fig_load_shift_heatmap(
    aware_df: pd.DataFrame,
    blind_df: pd.DataFrame,
    timeseries_df: pd.DataFrame,
) -> None:
    """Heatmap: (price quantile, methane number) -> load shift."""
    price_q = pd.qcut(timeseries_df["price_eur_mwh"], q=5, labels=False)
    ch4 = timeseries_df["CH4"]
    ch4_q = pd.qcut(ch4, q=5, labels=False)
    shift = aware_df["m_dot"] - blind_df["m_dot"]
    pivot = pd.DataFrame({"price_q": price_q, "ch4_q": ch4_q, "shift": shift})
    table = pivot.groupby(["price_q", "ch4_q"])["shift"].mean().unstack()
    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(table, annot=True, fmt=".1f", ax=ax, cmap="RdBu_r", center=0)
    ax.set_xlabel("CH4 quantile (proxy for methane number)")
    ax.set_ylabel("Price quantile")
    ax.set_title("Load shift: aware - blind (kg/s)")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig3_load_shift.pdf")
    plt.close(fig)


def fig_surrogate_eval(eval_df: pd.DataFrame) -> None:
    """Bar chart of per-channel MAE, RMSE, R² from the held-out test split."""
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    for ax, metric in zip(axes, ["MAE", "RMSE", "R2"]):
        ax.bar(eval_df["channel"], eval_df[metric], color="steelblue")
        ax.set_title(metric)
        ax.set_xlabel("Output channel")
        ax.tick_params(axis="x", rotation=30)
    axes[0].set_ylabel("Error (physical units)")
    axes[2].set_ylabel("R²")
    fig.suptitle("PINN surrogate — held-out test set (10%)")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig5_surrogate_eval.pdf")
    plt.close(fig)


def fig_surrogate_fidelity(fidelity_df: pd.DataFrame) -> None:
    """PINN-predicted cost error vs CoolProp ground truth."""
    err_pct = fidelity_df["pinn_cost_eur"] / fidelity_df["true_cost_eur"] - 1.0
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(err_pct * 100, bins=40, color="steelblue", edgecolor="white")
    ax.axvline(1.0, color="red", linestyle="--", label="1% threshold")
    ax.axvline(-1.0, color="red", linestyle="--")
    ax.set_xlabel("Cost prediction error (%)")
    ax.set_ylabel("Count")
    ax.set_title("PINN surrogate fidelity vs CoolProp ground truth")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_DIR / "fig4_fidelity.pdf")
    plt.close(fig)
